fix(Pagination): デザイン修正
4-design/for-ui pull request #1407
Opened 2023-07-21 02:17 UTC by Qs-F

## チケット

- Close #1325 

## 実装内容

- Paginationコンポーネントを新たに[デザイン](https://www.figma.com/file/FXAVXugpz9S1j3k8Lcs6au/For-UI-v1.1.9?type=design&node-id=315-9187&mode=design&t=ib5S9Jzr609PMMSN-11)に合わせて作成
  - `inputtable={true}`は未実装
- TablePaginationからPaginationを使うように修正
  - onChangePaginationをonChangePageに修正: Paginationはページ送りという意味なのでPageのほうが好ましい
- Tableの`disablePagination={false}`のときのデザインを更新
  - Pagination自体にはmargin等をもたせたくないのでそれに合わせた更新

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|        |        |

## 相談内容(あれば)

-

2023-07-21 08:52 UTC, locona requested changes
２点確認お願いします！

2023-07-21 08:52 UTC, locona commented on packages/for-ui/src/table/TablePagination.tsx
> +                      onClickPreviousPageButton?.(e);
このボタンは、onChangePage/onChangePagination の互換性はありますか？

2023-07-21 08:52 UTC, locona commented on packages/for-ui/src/table/Table.tsx
> +        <div className="flex w-full justify-center">
適応しちゃってるのがあるので、classname でもいいから右寄せにもできるようにするのってできたりしますか？

2023-07-24 00:35 UTC, Qs-F commented on packages/for-ui/src/table/TablePagination.tsx
> +                      onClickPreviousPageButton?.(e);
あります！挙動が確認できないのはよくなかったので、テストを追加しておきました https://github.com/4-design/for-ui/pull/1407/commits/2545600709edc617c6ad6de49057aef050b242a4

2023-07-24 01:54 UTC, Qs-F commented on packages/for-ui/src/table/Table.tsx
> +        <div className="flex w-full justify-center">
コンポーネントのルートにclassNameを適用するようにしました…！これでいかがでしょう？ https://github.com/4-design/for-ui/pull/1407/commits/24fe800a24e96e1fa89aecbf6ebd9fa8ed49508f

2023-07-24 11:31 UTC, locona approved these changes
LGTM

2023-07-25 01:32 UTC, merged