Fix/typescale text field@867
4-design/for-ui pull request #904
Opened 2022-12-01 22:28 UTC by kotobuki562

## チケット

- #867 

## 実装内容

- TextFieldのフォントサイズを16pxベースのところを14pxベースに変更
- MuiTextFieldのsize propsに"large"が存在しないため、fontSize propsを追加して対応

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|   ![screencapture-localhost-6006-2022-12-02-07_20_54](https://user-images.githubusercontent.com/67810971/205171431-98a7f5b5-3e52-456a-8acd-b547dfe95502.png)     |     ![screencapture-localhost-6006-2022-12-02-06_54_38](https://user-images.githubusercontent.com/67810971/205171252-82773bf8-aadd-4a7c-aeec-a87b2b99ae42.png)   |

## 相談内容(あれば)

- fontSize mediumの場合のクラス名"text-xs"のline-heightがFigmaと異なるがtailwind.config.jsの設定変更が必要か？もしくはクラス名直打ちで変更するか？
- MuiTextFieldのsize propsに"large"が存在しないためfontSize propsを追加して文字の大きさを変更できるようにしたがこの対応で問題ないか？

<img width="714" alt="スクリーンショット 2022-12-02 7 24 55" src="https://user-images.githubusercontent.com/67810971/205172235-019af277-f7e3-42d0-93c4-e38f4dfbc4a2.png">

2022-12-02 07:42 UTC, Qs-F requested changes
対応ありがとうございます！めっっっっちゃ助かります！！ 🙇 

数点些細な部分ですがコメントさせていただきました！

- `clsx` ではなく `fsx` を使うようにお願いします (コメントしきれてない部分も対応お願いします)
- largeではtext-r、mediumではtext-sで対応をお願いします！ (おそらくline heightのズレはそれが原因かなと… 🙇 )
  - Figma上との対応関係が少し名称が異なるのですが、
    - `r/regular` → `text-r`
    - `s/regular` → `tetx-s`
- `fontSize` props ではなく `size` propsにしたいです！

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +import clsx from 'clsx';
clsxではなくfsxのほうを使うようにお願いします！

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +  fontSize?: 'medium' | 'large';
fontSizeではなくsizeでいきたいですね… もしコンフリクトしてうまくいかない？ようであれば
`Omit<MuiTextFieldProps, 'size'>` に対して `size` propsを再定義する感じでお願いしたいです！
あとめっちゃ細かいところをもうしわけないんですが、順番は'large' | 'medium' でお願いできますと！

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +        className={clsx([other.className, 'text-right'])}
```suggestion
        className={fsx([other.className, 'text-right'])}
```

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +              root: clsx(['text-r text-shade-dark-default mr-3 font-sans antialiased']),
```suggestion
              root: fsx(['text-r text-shade-dark-default mr-3 font-sans antialiased']),
```

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +      <div className={clsx(['flex  flex-col', className])}>
```suggestion
      <div className={fsx(['flex  flex-col', className])}>
```

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +              className={clsx([
```suggestion
              className={fsx([
```

2022-12-02 07:42 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +                fontSize === 'medium' && 'text-xs',
```suggestion
                {
                  large: `text-r`,
                  medium: `text-s`,
                }[size]
```

でおねがいします！あとsizeはundefinedの場合はpropsでdefaultでlargeを仕込む感じでお願いしたいです！

2022-12-02 07:50 UTC, Qs-F commented
@kotobuki562

もしかしてテキストトークンのサイズのズレ、まだ未更新のtailwind.config.base.js のほうを使われているかもしれないです！
https://github.com/4-design/for-ui/pull/901
↑ここで更新をかけているので、checkout前のbranchを `fix/typescale@863` (PR: https://github.com/4-design/for-ui/pull/902 )にしてもらうと解決すると思います！(もしくはmergeしてもらうと！)

あとPRを出す先のbranchもmainではなく `fix/typescale@863` にお願いします！ (今回は自分の方で変えておきました！)

2022-12-04 00:23 UTC, kotobuki562 commented
@Qs-F 
こちら訂正しました！
selectコンポーネントでビルドエラー出ていたので解消しましたが、見た目上の変更は加えていません！

2022-12-05 06:58 UTC, Qs-F requested changes
@kotobuki562 

諸々修正ありがとうございます！こちらの手違いで間違った変更をお願いしてしまった箇所もあり…申し訳ないのですがもう少しだけ修正いただけますと助かります 🙇 すみません！

あとPRに関して、

- PRのタイトルについて、[これ](https://www.conventionalcommits.org/en/v1.0.0/)に習って付ける感じでおねがいしたく、今回だと
  - `fix(TextField): テキストのサイズダウンに伴うスタイル修正` とでもしておいていただけますと！
- branch `origin/fix/typescale@863` をこのPRにmergeしてもらえるとフォントサイズの情報が正しく設定されるはずなのでお願いします！

2022-12-05 06:58 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +      <div className={fsx(['flex  flex-col', className])}>
```suggestion
      <div className={fsx(['flex flex-col', className])}>
```

2022-12-05 06:58 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +                }[size],
すみません！ここすっかり勘違いしていたのですが、Labelなので
```suggestion
                'text-s text-shade-medium-default mb-1 font-bold',
```
でお願いします！

2022-12-05 06:58 UTC, Qs-F commented on packages/for-ui/src/select/Select.tsx
> +            size={size === 'medium' ? 'medium' : 'large'}
```suggestion
            size={size}
```
でいける気がしますがいかがでしょうか！

2022-12-05 06:58 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +                    medium: 'py-1.5 px-2 text-xs',
```suggestion
                    large: 'text-r py-2 px-4',
                    medium: 'text-s py-1.5 px-2',
```

でお願いします！

2022-12-05 06:58 UTC, Qs-F commented on packages/for-ui/src/textField/TextField.tsx
> +            size={size === 'medium' ? 'small' : 'medium'}
```suggestion
```


ここは消してしまっていいです (MUI側にsizeが渡らなくしてしまっていいです)

2022-12-05 22:03 UTC, kotobuki562 commented on packages/for-ui/src/select/Select.tsx
> +            size={size === 'medium' ? 'medium' : 'large'}
TSエラーが出てしまいますね🤔
size未指定か`size === 'medium' ? 'medium' : 'large'`で無理やり捩じ込むかかなあと🤔
他にいいやり方あったらご教授ください！

```
(property) size: "large" | "medium"
型 '"large" | "medium"' を型 '"small" | "medium" | undefined' に割り当てることはできません。
  型 '"large"' を型 '"small" | "medium" | undefined' に割り当てることはできません。

TextField.d.ts(148, 3): 予期された型は、型 'IntrinsicAttributes & LibraryManagedAttributes<(props: TextFieldProps) => Element, TextFieldProps>' に対してここで宣言されたプロパティ 'size' から取得されています
```

2022-12-05 22:05 UTC, kotobuki562 commented on packages/for-ui/src/textField/TextField.tsx
> +            size={size === 'medium' ? 'small' : 'medium'}
こちらで回答していただいていましたね💦

下記回答無視してください！
https://github.com/4-design/for-ui/pull/904#discussion_r1040146043

2022-12-05 22:07 UTC, kotobuki562 commented
@Qs-F 
修正箇所多くて恐れ入ります🙇
訂正しましたのでご確認ください！

2022-12-08 07:27 UTC, Qs-F approved these changes
遅くなってしまってすみません！LGTMです！

2022-12-08 12:34 UTC, merged