fix(Radio): テキストのサイズダウンに伴うスタイル修正
4-design/for-ui pull request #909
Opened 2022-12-05 22:44 UTC by kotobuki562

## チケット

- #905 

## 実装内容

- labelとのgapを8pxから4pxに
- paddingありのRadioを縦横24pxに
- indicator部分のサイズを16pxに
- hover時はborderの太さを変えず色だけ変える
- selectedなときはborderの太さを5pxに

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|    <img width="1202" alt="スクリーンショット 2022-12-06 7 43 33" src="https://user-images.githubusercontent.com/67810971/205758810-66719380-fdbe-466f-b828-4d1bb33590fa.png">    |   <img width="1208" alt="スクリーンショット 2022-12-06 7 43 20" src="https://user-images.githubusercontent.com/67810971/205758807-14b65e25-2efd-45fc-8fda-b54c31a0f16b.png">     |

## 相談内容(あれば)

- 特にありません

2022-12-06 09:44 UTC, Qs-F requested changes
ありがとうございます！

申し訳ないのですが、こちらのインストラクションの抜けがあったのと、デザインの変更をすこし加えたのでお手すきで対応いただけると助かります！
やっぱり実装されたものを触ってみると印象変わりますね… 🙇

2022-12-06 21:34 UTC, kotobuki562 commented
@Qs-F 
細かく見てくださりありがとうございます！
訂正しましたのでご確認ください！

2022-12-07 12:19 UTC, Qs-F requested changes
こちらこそ細かいところまで対応していただいて助かっております…！
申し訳ないです…！あと2点だけお願いします！

2022-12-07 12:19 UTC, Qs-F commented on packages/for-ui/src/radio/Radio.tsx
> +      root: fsx(['group hover:bg-transparent', nopadding ? 'p-0' : 'p-6']),
```suggestion
      root: fsx(['group hover:bg-transparent', nopadding ? 'p-0' : 'p-1']),
```

でお願いします！

2022-12-07 12:19 UTC, Qs-F commented on packages/for-ui/src/radio/Radio.tsx
> +      checked ? 'border-6' : 'group-hover:border-3 group-hover:border-secondary-dark-default border-2',
```suggestion
      checked ? 'border-6' : 'group-hover:border-secondary-dark-default border-2',
```

すみませんここ消しちゃって良いです！

2022-12-09 07:38 UTC, merged