fix(Checkbox): テキストのサイズダウンに伴うスタイル修正
4-design/for-ui pull request #914
Opened 2022-12-06 22:39 UTC by kotobuki562

## チケット

- #906

## 実装内容

- checkboxとlabelのgapを4pxにした

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|        |        |

## 相談内容(あれば)

- "現在MUIを使っている部分を再定義"とは自作でcheckboxを実装するという意味でよろしいでしょうか？？

2022-12-07 12:07 UTC, Qs-F requested changes
ありがとうございます！ちょっと質問をうけて自分でやってみてたんですが、思ったよりも面倒な対応になりそうだったので一旦これでOKにしたいと思います！
Radioの修正だけ抜いておいてもらえますと！

2022-12-07 22:13 UTC, kotobuki562 commented
結構しんどそうですよね〜🤔
あ、Checkboxの更新も入ってるの気づきませんでした🙏
ていせいしますね！

2022-12-07 22:49 UTC, kotobuki562 commented
@Qs-F 
こちら修正しました！

2022-12-08 07:34 UTC, Qs-F approved these changes
対応ありがとうございました！LGTMです〜〜〜！！

2022-12-09 05:44 UTC, merged