fix(Switch): テキストのサイズダウンに伴うスタイル修正
4-design/for-ui pull request #919
Opened 2022-12-08 22:01 UTC by kotobuki562

## チケット

- #870 

## 実装内容

- サイズの調整
toggleの大きさを4remに
p-0.5 にする
横幅は32pxになるように

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|   <img width="628" alt="スクリーンショット 2022-12-09 6 57 29" src="https://user-images.githubusercontent.com/67810971/206576285-f9dcbd10-09d3-4a3a-bdfa-047f36c0935f.png">     |    <img width="594" alt="スクリーンショット 2022-12-09 6 56 35" src="https://user-images.githubusercontent.com/67810971/206576310-426033d4-fe78-4e36-951d-84365c5e6fcf.png">    |

## 相談内容(あれば)

- toggleのサイズや可動域をかなり無理やり調整した感があります...脱muiした方が管理しやすいかもです👀

2022-12-09 06:21 UTC, Qs-F requested changes
ありがとうございます！
改修をお願いしたいところを3点ほど書きました！

また、今回の担当していただいた範囲外なんですが、SwitchPropsのdisableを消しておいてもらえると助かります！ (SwitchPropsにdisabledは存在していてdisableはスペルミスで必要ないものと考えられるため)

2022-12-09 06:21 UTC, Qs-F commented on packages/for-ui/src/switch/Switch.tsx
> +            root: fsx(['my-2 mr-2 h-5 w-8 p-0.5']),
```suggestion
            root: fsx(['m-0 p-0 w-auto h-auto flex']),
```

でお願いします！

2022-12-09 06:21 UTC, Qs-F commented on packages/for-ui/src/switch/Switch.tsx
>                'bg-primary-dark-default block h-full w-full rounded-xl opacity-100',
```suggestion
              'bg-primary-dark-default block h-5 w-8 rounded-xl opacity-100',
```

大きさの指定はこっちで行いたいです！

2022-12-09 06:21 UTC, Qs-F commented on packages/for-ui/src/switch/Switch.tsx
> +              'bg-shade-white-default absolute top-1 left-1 h-3 w-3 rounded-2xl transition-all duration-200 ease-in-out',
```suggestion
              'bg-shade-white-default absolute top-0.5 left-0.5 h-4 w-4 rounded-2xl transition-all duration-200 ease-in-out shadow-none',
```

2022-12-09 07:25 UTC, Qs-F commented
@kotobuki562 

すみません、相談内容を見逃していました。たしかにtransformは結構辛い気がするので、こんな感じでいかがでしょうか？
```ts
          classes={{
            root: fsx('p-0 flex m-0 w-auto h-auto'),
            track: fsx([
              'bg-primary-dark-default block h-full w-full rounded-xl opacity-100 h-5 w-8',
              checked && 'bg-secondary-dark-default opacity-100',
              disabled && 'bg-primary-dark-disabled opacity-100',
              checked && disabled && 'bg-secondary-dark-disabled opacity-100',
            ]),
            thumb: fsx([
              'bg-shade-white-default h-4 w-4 rounded-2xl shadow-none',
            ]),
            switchBase: fsx([
              'm-0.5 p-0 transition-all duration-100 ease-in-out',
            ]),
            checked: fsx([
              'transform-none pl-3'
            ]),
          }}
```

2022-12-11 05:42 UTC, kotobuki562 commented
> @kotobuki562
> 
> すみません、相談内容を見逃していました。たしかにtransformは結構辛い気がするので、こんな感じでいかがでしょうか？

了解です！
挙動確認したところ問題なさそうなのでこちらを使用させていただきます！！

2022-12-12 08:52 UTC, Qs-F requested changes
すみません！伝え忘れていました 🙇 
FormControlLabelに
```ts
      classes={{
        root: fsx(['m-0 flex gap-1']),
        label: fsx(['text-r text-shade-dark-default font-sans']),
      }}
```

を追加していただけますと！(全体のコードは前回のreviewのものを参考にしてください)

2022-12-13 22:50 UTC, kotobuki562 commented
@Qs-F 
訂正して追加しました！

2022-12-14 08:44 UTC, Qs-F approved these changes
確認しました！完璧です、ありがとうございます！！

2022-12-14 08:53 UTC, merged