feat: Chipコンポーネントの新デザイン実装
4-design/for-ui pull request #943
Opened 2022-12-21 00:53 UTC by kotobuki562

## チケット

- #871 

## 実装内容

- Chipコンポーネントの新デザインを実装

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|    <img width="1003" alt="スクリーンショット 2022-12-21 9 36 34" src="https://user-images.githubusercontent.com/67810971/208793362-ea44e9fe-38a1-44d4-a3eb-194042529be8.png">    |    <img width="912" alt="スクリーンショット 2022-12-21 9 22 42" src="https://user-images.githubusercontent.com/67810971/208793289-3d0c3c10-5293-4a1f-a770-eb7ff077435c.png">    |

## 相談内容(あれば)

- Mui依存だと見た目形成がしんどいので自前で実装した方がいいかも？

2022-12-23 12:38 UTC, Qs-F requested changes
レビューが遅くなってしまってすみません！

- hover時の状態について、onDeleteのほうは全体でのhoverをなくしたいです！

あとアイコンをコメントさせていただいたので、お時間あるときに変更いただけると助かります！

2022-12-23 12:38 UTC, Qs-F commented on packages/for-ui/src/chip/Chip.stories.tsx
> +import { BsPaperclip } from 'react-icons/bs';
MdAttachFileをつかってください！

```suggestion
import { MdAttachFile } from 'react-icons/md'
```

2022-12-23 23:57 UTC, kotobuki562 commented
@Qs-F 
レビューありがとうございます！
変更しました！

2022-12-26 04:22 UTC, Qs-F approved these changes
めっちゃ良いです！ ありがとうございますー！！

2023-01-12 07:30 UTC, merged