fix(Badge): Badgeコンポーネントのデザイン実装
4-design/for-ui pull request #954
Opened 2022-12-26 12:18 UTC by kotobuki562

## チケット

- #908 

## 実装内容

- Badgeコンポーネントの新デザイン実装

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|   <img width="683" alt="スクリーンショット 2022-12-26 21 17 43" src="https://user-images.githubusercontent.com/67810971/209548188-85d46f76-58eb-4882-89fb-2814d0d6ad7e.png">     |     <img width="681" alt="スクリーンショット 2022-12-26 21 17 13" src="https://user-images.githubusercontent.com/67810971/209548144-d8454bc5-073d-4274-9c89-52a87c5b354c.png">   |

## 相談内容(あれば)

- muiベースだと実装厳しそうなのでプロパティだけ引き継ぎました

2022-12-28 07:16 UTC, Qs-F requested changes
レビュー遅くなってしまってすみません 🙇  ありがとうございます！！
些末なことを少しだけ書かせてもらったので、確認して変更いただけますと幸いです…！

2022-12-28 07:16 UTC, Qs-F commented on .changeset/hip-seas-wash.md
> +"@4design/for-ui": patch
```suggestion
"@4design/for-ui": minor
```

でお願いします 🙇

2022-12-28 07:16 UTC, Qs-F commented on packages/for-ui/src/badge/Badge.tsx
> +  type?: 'constant' | 'text' | 'outline';
variantでお願いします…！

```suggestion
  variant?: 'constant' | 'text' | 'outline';
```

2022-12-28 07:16 UTC, Qs-F commented on packages/for-ui/src/badge/Badge.tsx
> +            <MdError className="h-4 w-4" />
すみません！ここのアイコンも変えられるようにしたく…

```suggestion
            {icon}
```

でおねがいします！

2022-12-28 07:16 UTC, Qs-F commented on packages/for-ui/src/badge/Badge.tsx
> +            <MdError className="h-4 w-4" />
すみません！ここのアイコンも変えられるようにしたく…

```suggestion
            {icon}
```

2022-12-28 07:16 UTC, Qs-F commented on packages/for-ui/src/badge/Badge.tsx
> +    default:
switchを使うときはdefaultがあるとexhaustiveにならず今後対応漏れが出てきたときに型で気づきにくくなるので、default句を書かないようにしたいです！

2022-12-28 22:03 UTC, kotobuki562 commented
@Qs-F 
こちら修正しました！

2023-01-06 07:45 UTC, Qs-F approved these changes
https://github.com/4-design/for-ui/pull/954/files#r1060628443
これは私も同意です！

そこ以外はLGTMです！ありがとうございます〜！！！

2023-01-09 22:18 UTC, kotobuki562 commented on packages/for-ui/src/badge/Badge.tsx
> +            'flex flex-row items-start gap-1 rounded',
確かにここちょっと悩んでました！
修正しました！レビューありがとうございます！

2023-01-10 08:43 UTC, locona commented on packages/for-ui/src/badge/index.tsx
> +export * from './ConstantBadge';
こちらinterface はBadge で共通なので、export する必要ないです！

2023-01-17 10:48 UTC, merged