fix(Switch): Switchコンポーネンの新デザイン実装
4-design/for-ui pull request #963
Opened 2022-12-30 00:16 UTC by kotobuki562

## チケット

-

## 実装内容

-

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|        |     <img width="313" alt="スクリーンショット 2022-12-30 8 17 16" src="https://user-images.githubusercontent.com/67810971/210022652-49325796-65a4-4ecb-ae2e-f41c9254af90.png">   |

## 相談内容(あれば)

-

2023-01-03 14:21 UTC, locona requested changes

2023-01-03 14:21 UTC, locona commented on packages/for-ui/src/switch/Switch.tsx
> +            checked && disabled && 'bg-[#AFE2F8]',
このカラーはテーマカラーに直す予定ですかね？

2023-01-03 15:48 UTC, Qs-F commented on packages/for-ui/src/switch/Switch.tsx
> +            checked && disabled && 'bg-[#AFE2F8]',
この対応はあとで仕込む (Badgeも同じ) 予定です！

2023-01-06 07:31 UTC, Qs-F requested changes
ありがとうございます！
すみません、inputをabsoluteでz-indexでかぶせることはあまりしたくなく… (absoluteを極力コンポーネント内部で使いたくないため) 変わりの実装を書いてみました！見てもらえると嬉しいです〜

```ts
import { forwardRef } from 'react';
import FormControlLabel, { FormControlLabelProps } from '@mui/material/FormControlLabel';
import { fsx } from '../system/fsx';

export type SwitchProps<Value = unknown> = Omit<FormControlLabelProps, 'control'> & {
  value?: Value;
};

export const Switch = forwardRef<HTMLInputElement, SwitchProps>((props, ref) => (
  <FormControlLabel
    classes={{
      root: fsx(['m-0 flex gap-1']),
      label: fsx(['text-r text-shade-dark-default font-sans']),
    }}
    control={
      <input
        type="checkbox"
        ref={ref}
        className={fsx([
          `appearance-none bg-shade-medium-default rounded-full h-5 w-8 p-0.5 transition-all duration-100 cursor-pointer`,
          `before:content-[''] before:block before:h-4 before:w-4 before:bg-shade-white-default before:rounded-full`,
          `checked:bg-primary-dark-default checked:pl-3.5`,
          `disabled:cursor-not-allowed disabled:bg-shade-medium-disabled`,
          `disabled:checked:bg-primary-dark-disabled`,
        ])}
      />
    }
    {...props}
  />
));
```

2023-01-06 07:31 UTC, Qs-F commented on .changeset/eight-months-cross.md
> +"@4design/for-ui": patch
```suggestion
"@4design/for-ui": minor
```

2023-01-06 07:33 UTC, Qs-F commented
あとすみません、Storybookにお手すきでReact Hook Formのregisterを使った例も載せておいていただけると嬉しいです…！

```ts
import React from 'react';
import { Meta } from '@storybook/react/types-6-0';

import { Controller, useForm } from 'react-hook-form';
import { Button } from '../button';
import { Switch } from './Switch';
import { SwitchGroup } from './SwitchGroup';
import * as yup from 'yup';
import { yupResolver } from '@hookform/resolvers/yup';

export default {
  title: 'Form / Switch',
  component: Switch,
  argTypes: {},
} as Meta;

export const Basic = (): JSX.Element => {
  const { control, handleSubmit } = useForm<{
    default1: boolean;
    default2: boolean;
    disable1: boolean;
    disable2: boolean;
  }>({
    reValidateMode: 'onChange',
  });

  const onSubmit = (data: unknown) => console.info(data);

  return (
    <div className="flex flex-row gap-4">
      <form onSubmit={handleSubmit(onSubmit)}>
        <SwitchGroup required label="サービス名">
          <Controller
            control={control}
            name="default1"
            defaultValue={false}
            render={({ field: { name, value, onChange } }) => {
              return <Switch name={name} label="default1" checked={value} onChange={onChange} />;
            }}
          />
          <Controller
            control={control}
            name="default2"
            defaultValue={true}
            render={({ field: { name, value, onChange } }) => {
              return <Switch name={name} label="default2" checked={value} onChange={onChange} />;
            }}
          />
          <Controller
            control={control}
            name="disable1"
            defaultValue={false}
            render={({ field: { name, value, onChange } }) => {
              return <Switch name={name} label="disable1" checked={value} disabled onChange={onChange} />;
            }}
          />
          <Controller
            control={control}
            name="disable2"
            defaultValue={true}
            render={({ field: { name, value, onChange } }) => {
              return <Switch name={name} label="disable2" checked={value} disabled onChange={onChange} />;
            }}
          />
        </SwitchGroup>

        <div className="mt-8">
          <Button type="submit">登録する</Button>
        </div>
      </form>
    </div>
  );
};

const schema = yup.object({
  autosave: yup.string().required(),
});

type FieldValue = yup.InferType<typeof schema>;

export const WithReactHookForm = () => {
  const { register, handleSubmit } = useForm<FieldValue>({
    resolver: yupResolver(schema),
  });
  const onSubmit = (data: unknown) => {
    console.info(data);
  };

  return (
    <form className="w-96" onSubmit={handleSubmit(onSubmit)}>
      <Switch label="自動保存" {...register('autosave')} />
      <Button type="submit">送信</Button>
    </form>
  );
};
```

2023-01-09 22:21 UTC, kotobuki562 commented on packages/for-ui/src/switch/Switch.tsx
> +            checked && disabled && 'bg-[#AFE2F8]',
青ではなくオレンジに変更します？🤔

2023-01-09 22:25 UTC, kotobuki562 commented on .changeset/eight-months-cross.md
> +"@4design/for-ui": patch
確認しました！
正常に動いていましたので適用しました！

2023-01-09 22:26 UTC, kotobuki562 commented
storiesも修正しておきました！

2023-01-10 09:11 UTC, Qs-F commented on packages/for-ui/src/switch/Switch.tsx
> +            checked && disabled && 'bg-[#AFE2F8]',
というより、Tokenで定義されているので、FigmaのTokenで揃えておくとサービスごとに固有の色にできるという感じです！

2023-01-10 09:12 UTC, Qs-F commented on .changeset/eight-months-cross.md
> +"@4design/for-ui": patch
ありがとうございます！

2023-01-12 10:27 UTC, Qs-F requested changes
changesetのpatchをminorに直すのだけお願いします！

2023-01-12 10:27 UTC, Qs-F commented on .changeset/eight-months-cross.md
> +"@4design/for-ui": patch
@kotobuki562 
patchをminorに直すのだけお願いします！

2023-01-12 22:35 UTC, kotobuki562 commented
こちら変更しました！

2023-01-19 06:38 UTC, Qs-F approved these changes
LGTMです！ありがとうございますー！！！

2023-01-20 05:14 UTC, locona approved these changes
LGTM

2023-01-24 10:22 UTC, merged