テーブルのサイズを変更
4-design/for-ui pull request #976
Opened 2023-01-08 01:02 UTC by kotobuki562

## チケット

- #872 

## 実装内容

- Tableサイズの変更

## スクリーンショット

| 変更前 | 変更後 |
| ------ | ------ |
|    <img width="847" alt="スクリーンショット 2023-01-08 7 35 23" src="https://user-images.githubusercontent.com/67810971/211172841-d7c3932b-3bc8-4def-8f14-d0ca44bc1ee6.png">    |     <img width="850" alt="スクリーンショット 2023-01-08 7 34 08" src="https://user-images.githubusercontent.com/67810971/211172811-3b66acc7-62e5-4227-a313-eab4dae1a492.png">   |

## 相談内容(あれば)

-

2023-01-17 22:36 UTC, kotobuki562 commented
ローカルではビルドが成功する🤔

<img width="598" alt="スクリーンショット 2023-01-18 7 36 35" src="https://user-images.githubusercontent.com/67810971/213027432-3b735347-3d9e-43a4-a493-edb9d3065a85.png">

2023-01-19 04:31 UTC, Qs-F requested changes
ありがとうございますー！
すみません、2点だけ修正お願いします 🙇

2023-01-19 04:31 UTC, Qs-F commented on .changeset/fluffy-bobcats-peel.md
> +"@4design/for-ui": patch
```suggestion
"@4design/for-ui": minor
```

minorでお願いします！

2023-01-19 04:31 UTC, Qs-F commented on packages/for-ui/src/table/Table.tsx
> +import { LegacyText } from '../typography';
```suggestion
import { Text } from '../text';
```

LegacyTextではなくTextのほうを使ってほしいです！

2023-01-21 07:33 UTC, kotobuki562 commented
修正しました！

2023-01-21 10:56 UTC, Qs-F approved these changes
ありがとうございます！！LGTMです 👍

2023-01-24 10:22 UTC, merged